spring:
    datasource:
        url: jdbc:mysql://localhost:3306/greeny_db
        username: root
        password: abcABC123!@#
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: MySQL
        database-platform: org.hibernate.dialect.MySQLDialect

    mqtt:
        client-id: spring_mqtt_client
        username: GreenyServer
        password: GreenyServer123
        url: ssl://e5dfb536a0a1462aa9e5c9a81159c869.s1.eu.hivemq.cloud:8883
        default-topic: home/temperature
server:
  port: 8443
  ssl:
    key-store: classpath:keystore_greeny.p12
    key-store-password: greeny
    key-store-type: PKCS12
    key-alias: greeny